//---------------------------------------------------------------------------

#ifndef TRGSMprUnit3H
#define TRGSMprUnit3H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <TabNotBk.hpp>
#include <ExtCtrls.hpp>
#include <Dialogs.hpp>
#include <IdBaseComponent.hpp>
#include <IdComponent.hpp>
#include <IdTCPClient.hpp>
#include <IdTCPConnection.hpp>
#include <IdTelnet.hpp>
#include <Menus.hpp>
#include <Buttons.hpp>
#include "WinSkinData.hpp"
#include "WinSkinForm.hpp"
//---------------------------------------------------------------------------
class TForm3 : public TForm
{
__published:	// IDE-managed Components
        TButton *Button1;
        TButton *Button2;
        TSaveDialog *SaveDialog1;
        TOpenDialog *OpenDialog1;
        TMainMenu *MainMenu1;
        TMenuItem *File1;
        TMenuItem *Loadfromsystem1;
        TMenuItem *Load1;
        TMenuItem *Saveas1;
        TIdTelnet *IdTelnet1;
        TMenuItem *Options1;
        TPageControl *PageControl1;
        TTabSheet *TabSheet1;
        TPanel *Panel1;
        TLabel *Label1;
        TLabel *Label2;
        TLabel *SitenoLabel;
        TLabel *Label3;
        TMemo *Rbltbuffer;
        TMemo *Tgbuffer;
        TMemo *Bufferf3;
        TComboBox *Csystype;
        TEdit *Siteno;
        TComboBox *Fhop;
        TComboBox *Seksay;
        TGroupBox *TG;
        TLabel *TgLabel;
        TLabel *Tg1Label;
        TLabel *Tg2Label;
        TLabel *Tg3Label;
        TLabel *Tg4Label;
        TEdit *Tg1;
        TEdit *Tg2;
        TEdit *Tg3;
        TEdit *Tg4;
        TComboBox *Tgsayi;
        TGroupBox *GroupBox1;
        TLabel *RbltsayiLabel;
        TLabel *Rblt1Label;
        TLabel *Rblt2Label;
        TLabel *Rblt3Label;
        TLabel *Rblt4Label;
        TComboBox *Rbltsayi;
        TEdit *Rblt1;
        TEdit *Rblt2;
        TEdit *Rblt3;
        TEdit *Rblt4;
        TGroupBox *Edge;
        TGroupBox *GroupBox2;
        TRadioButton *Edgevar;
        TRadioButton *Edgeyoxdu;
        TTabSheet *TabSheet2;
        TTabSheet *TabSheet6;
        TGroupBox *GroupBox3;
        TPanel *RxappPanel;
        TPanel *RxtcpPanel;
        TPageControl *PageControl2;
        TTabSheet *TabSheet7;
        TTabSheet *TabSheet8;
        TTabSheet *TabSheet9;
        TTabSheet *TabSheet10;
        TGroupBox *K1;
        TLabel *TpLabelk1;
        TLabel *Label8;
        TLabel *Label12;
        TLabel *Label24;
        TLabel *Label85;
        TPanel *Tru1k1;
        TEdit *Chgrtru1k1;
        TPanel *Etru1k1;
        TPanel *Tru3k1;
        TEdit *Chgrtru3k1;
        TPanel *Etru3k1;
        TPanel *Tru7k1;
        TEdit *Chgrtru7k1;
        TPanel *Etru7k1;
        TPanel *Tru5k1;
        TEdit *Chgrtru5k1;
        TPanel *Etru5k1;
        TPanel *Tru8k1;
        TEdit *Chgrtru8k1;
        TPanel *Etru8k1;
        TPanel *Tru6k1;
        TEdit *Chgrtru6k1;
        TPanel *Etru6k1;
        TPanel *Tru4k1;
        TEdit *Chgrtru4k1;
        TPanel *Etru4k1;
        TPanel *Tru11k1;
        TEdit *Chgrtru11k1;
        TPanel *Etru11k1;
        TPanel *Tru9k1;
        TEdit *Chgrtru9k1;
        TPanel *Etru9k1;
        TPanel *Tru12k1;
        TEdit *Chgrtru12k1;
        TPanel *Etru12k1;
        TPanel *Tru10k1;
        TEdit *Chgrtru10k1;
        TPanel *Etru10k1;
        TComboBox *Tpk1;
        TPanel *Tru2k1;
        TEdit *Chgrtru2k1;
        TPanel *Etru2k1;
        TComboBox *Tgk1;
        TComboBox *Tfmodek1;
        TGroupBox *Dxuk1;
        TLabel *Label16;
        TLabel *Label17;
        TSpeedButton *Pbodp01k1;
        TSpeedButton *Pbodp23k1;
        TComboBox *Odp01k1;
        TCheckBox *Odp0k1;
        TCheckBox *Odp1k1;
        TComboBox *Odp23k1;
        TCheckBox *Odp2k1;
        TCheckBox *Odp3k1;
        TComboBox *Swverk1;
        TComboBox *Teik1;
        TPanel *Ppodp01k1;
        TLabel *Label35;
        TLabel *Label36;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TLabel *Label40;
        TLabel *Label41;
        TEdit *Pe1odp01k1;
        TEdit *Pe2odp01k1;
        TEdit *Pe3odp01k1;
        TEdit *Pe5odp01k1;
        TEdit *Pe4odp01k1;
        TEdit *Pe6odp01k1;
        TPanel *Eodp01k1;
        TPanel *Ppodp23k1;
        TLabel *Label28;
        TLabel *Label29;
        TLabel *Label30;
        TLabel *Label31;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label34;
        TEdit *Pe1odp23k1;
        TEdit *Pe2odp23k1;
        TEdit *Pe3odp23k1;
        TEdit *Pe4odp23k1;
        TEdit *Pe5odp23k1;
        TEdit *Pe6odp23k1;
        TPanel *Eodp23k1;
        TGroupBox *K2;
        TLabel *Label4;
        TLabel *Label9;
        TLabel *Label13;
        TLabel *Label25;
        TLabel *Label86;
        TComboBox *Tpk2;
        TPanel *Tru1k2;
        TEdit *Chgrtru1k2;
        TPanel *Etru1k2;
        TPanel *Tru3k2;
        TEdit *Chgrtru3k2;
        TPanel *Etru3k2;
        TPanel *Tru5k2;
        TEdit *Chgrtru5k2;
        TPanel *Etru5k2;
        TPanel *Tru7k2;
        TEdit *Chgrtru7k2;
        TPanel *Etru7k2;
        TPanel *Tru9k2;
        TEdit *Chgrtru9k2;
        TPanel *Etru9k2;
        TPanel *Tru11k2;
        TEdit *Chgrtru11k2;
        TPanel *Etru11k2;
        TPanel *Tru2k2;
        TEdit *Chgrtru2k2;
        TPanel *Etru2k2;
        TPanel *Tru4k2;
        TEdit *Chgrtru4k2;
        TPanel *Etru4k2;
        TPanel *Tru6k2;
        TEdit *Chgrtru6k2;
        TPanel *Etru6k2;
        TPanel *Tru8k2;
        TEdit *Chgrtru8k2;
        TPanel *Etru8k2;
        TPanel *Tru10k2;
        TEdit *Chgrtru10k2;
        TPanel *Etru10k2;
        TPanel *Tru12k2;
        TEdit *Chgrtru12k2;
        TPanel *Etru12k2;
        TComboBox *Tgk2;
        TComboBox *Tfmodek2;
        TGroupBox *Dxuk2;
        TLabel *Label18;
        TLabel *Label21;
        TSpeedButton *Pbodp01k2;
        TSpeedButton *Pbodp23k2;
        TComboBox *Odp01k2;
        TComboBox *Odp23k2;
        TCheckBox *Odp0k2;
        TCheckBox *Odp1k2;
        TCheckBox *Odp2k2;
        TCheckBox *Odp3k2;
        TComboBox *Swverk2;
        TComboBox *Teik2;
        TPanel *Ppodp01k2;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label55;
        TEdit *Pe1odp01k2;
        TEdit *Pe2odp01k2;
        TEdit *Pe3odp01k2;
        TEdit *Pe4odp01k2;
        TEdit *Pe5odp01k2;
        TEdit *Pe6odp01k2;
        TPanel *Eodp01k2;
        TPanel *Ppodp23k2;
        TLabel *Label42;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label54;
        TEdit *Pe1odp23k2;
        TEdit *Pe3odp23k2;
        TEdit *Pe5odp23k2;
        TEdit *Pe2odp23k2;
        TEdit *Pe4odp23k2;
        TEdit *Pe6odp23k2;
        TPanel *Eodp23k2;
        TGroupBox *K3;
        TLabel *Label6;
        TLabel *Label10;
        TLabel *Label14;
        TLabel *Label26;
        TLabel *Label84;
        TComboBox *Tpk3;
        TPanel *Tru1k3;
        TEdit *Chgrtru1k3;
        TPanel *Etru1k3;
        TPanel *Tru3k3;
        TEdit *Chgrtru3k3;
        TPanel *Etru3k3;
        TPanel *Tru5k3;
        TEdit *Chgrtru5k3;
        TPanel *Etru5k3;
        TPanel *Tru7k3;
        TEdit *Chgrtru7k3;
        TPanel *Etru7k3;
        TPanel *Tru9k3;
        TEdit *Chgrtru9k3;
        TPanel *Etru9k3;
        TPanel *Tru11k3;
        TEdit *Chgrtru11k3;
        TPanel *Etru11k3;
        TPanel *Tru2k3;
        TEdit *Chgrtru2k3;
        TPanel *Etru2k3;
        TPanel *Tru4k3;
        TEdit *Chgrtru4k3;
        TPanel *Etru4k3;
        TPanel *Tru6k3;
        TEdit *Chgrtru6k3;
        TPanel *Etru6k3;
        TPanel *Tru8k3;
        TEdit *Chgrtru8k3;
        TPanel *Etru8k3;
        TPanel *Tru10k3;
        TEdit *Chgrtru10k3;
        TPanel *Etru10k3;
        TPanel *Tru12k3;
        TEdit *Chgrtru12k3;
        TPanel *Etru12k3;
        TComboBox *Tgk3;
        TComboBox *Tfmodek3;
        TGroupBox *Dxuk3;
        TLabel *Label19;
        TLabel *Label22;
        TSpeedButton *Pbodp01k3;
        TSpeedButton *Pbodp23k3;
        TComboBox *Odp01k3;
        TComboBox *Odp23k3;
        TCheckBox *Odp0k3;
        TCheckBox *Odp1k3;
        TCheckBox *Odp2k3;
        TCheckBox *Odp3k3;
        TComboBox *Swverk3;
        TComboBox *Teik3;
        TPanel *Ppodp01k3;
        TLabel *Label56;
        TLabel *Label60;
        TLabel *Label61;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TLabel *Label65;
        TEdit *Pe2odp01k3;
        TEdit *Pe4odp01k3;
        TEdit *Pe1odp01k3;
        TEdit *Pe3odp01k3;
        TEdit *Pe5odp01k3;
        TEdit *Pe6odp01k3;
        TPanel *Eodp01k3;
        TPanel *Ppodp23k3;
        TLabel *Label57;
        TLabel *Label66;
        TLabel *Label67;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *Label71;
        TEdit *Pe1odp23k3;
        TEdit *Pe2odp23k3;
        TEdit *Pe3odp23k3;
        TEdit *Pe4odp23k3;
        TEdit *Pe5odp23k3;
        TEdit *Pe6odp23k3;
        TPanel *Eodp23k3;
        TGroupBox *K4;
        TLabel *Label5;
        TLabel *Label11;
        TLabel *Label15;
        TLabel *Label27;
        TLabel *Label87;
        TComboBox *Tpk4;
        TPanel *Tru1k4;
        TEdit *Chgrtru1k4;
        TPanel *Etru1k4;
        TPanel *Tru3k4;
        TEdit *Chgrtru3k4;
        TPanel *Etru3k4;
        TPanel *Tru5k4;
        TEdit *Chgrtru5k4;
        TPanel *Etru5k4;
        TPanel *Tru7k4;
        TEdit *Chgrtru7k4;
        TPanel *Etru7k4;
        TPanel *Tru9k4;
        TEdit *Chgrtru9k4;
        TPanel *Etru9k4;
        TPanel *Tru11k4;
        TEdit *Chgrtru11k4;
        TPanel *Etru11k4;
        TPanel *Tru2k4;
        TEdit *Chgrtru2k4;
        TPanel *Etru2k4;
        TPanel *Tru4k4;
        TEdit *Chgrtru4k4;
        TPanel *Etru4k4;
        TPanel *Tru6k4;
        TEdit *Chgrtru6k4;
        TPanel *Etru6k4;
        TPanel *Tru8k4;
        TEdit *Chgrtru8k4;
        TPanel *Etru8k4;
        TPanel *Tru10k4;
        TEdit *Chgrtru10k4;
        TPanel *Etru10k4;
        TPanel *Tru12k4;
        TEdit *Chgrtru12k4;
        TPanel *Etru12k4;
        TComboBox *Tgk4;
        TComboBox *Tfmodek4;
        TGroupBox *Dxuk4;
        TLabel *Label20;
        TLabel *Label23;
        TSpeedButton *Pbodp01k4;
        TSpeedButton *Pbodp23k4;
        TComboBox *Odp01k4;
        TComboBox *Odp23k4;
        TCheckBox *Odp0k4;
        TCheckBox *Odp2k4;
        TCheckBox *Odp1k4;
        TCheckBox *Odp3k4;
        TComboBox *Swverk4;
        TComboBox *Teik4;
        TPanel *Ppodp01k4;
        TLabel *Label59;
        TLabel *Label75;
        TLabel *Label76;
        TLabel *Label77;
        TLabel *Label78;
        TLabel *Label79;
        TLabel *Label80;
        TEdit *Pe1odp01k4;
        TEdit *Pe3odp01k4;
        TEdit *Pe5odp01k4;
        TEdit *Pe2odp01k4;
        TEdit *Pe4odp01k4;
        TEdit *Pe6odp01k4;
        TPanel *Eodp01k4;
        TPanel *Ppodp23k4;
        TLabel *Label58;
        TLabel *Label72;
        TLabel *Label73;
        TLabel *Label74;
        TLabel *Label81;
        TLabel *Label82;
        TLabel *Label83;
        TEdit *Pe1odp23k4;
        TEdit *Pe2odp23k4;
        TEdit *Pe3odp23k4;
        TEdit *Pe4odp23k4;
        TEdit *Pe5odp23k4;
        TEdit *Pe6odp23k4;
        TPanel *Eodp23k4;
        TGroupBox *Skt;
        TRadioButton *Skt1;
        TRadioButton *Skt2;
        TRadioButton *Skt3;
        TRadioButton *Skt4;
        TRadioButton *Deskt;
        TPanel *RlbdpPanel;
        TPanel *RxmopPanel;
        TPanel *RldepPanel;
        TPanel *Rxmoptruk1Panel;
        TPanel *Rxmoptruk2Panel;
        TPanel *Rxmoptruk3Panel;
        TPanel *Rxmoptruk4Panel;
        TPanel *Cell1Panel;
        TPanel *Cell2Panel;
        TPanel *Cell3Panel;
        TPanel *Cell4Panel;
        TPanel *AdditionPanel;
        TLabel *Label7;
        TComboBox *Ksayi;
        TMemo *Memo1;
        TMemo *Memo2;
        TPageControl *PageControl3;
        TTabSheet *Edgec1;
        TTabSheet *Edgec2;
        TTabSheet *Edgec3;
        TTabSheet *Edgec4;
        TGroupBox *Edgec1Panel;
        TLabel *Label88;
        TLabel *Label89;
        TLabel *Label90;
        TLabel *Label91;
        TLabel *Label95;
        TEdit *Numreqbpcch1c1;
        TEdit *Numreqbpcch0c1;
        TEdit *Numreqegprsbpcch0c1;
        TEdit *Tn7bcchch0c1;
        TEdit *Numreqcs3cs4bpcch0c1;
        TEdit *Numreqegprsbpcch1c1;
        TEdit *Numreqcs3cs4bpcch1c1;
        TEdit *Cell1;
        TGroupBox *Edgec2Panel;
        TLabel *Label92;
        TLabel *Label93;
        TLabel *Label94;
        TLabel *Label97;
        TLabel *Label99;
        TEdit *Numreqbpcch0c2;
        TEdit *Numreqegprsbpcch0c2;
        TEdit *Numreqcs3cs4bpcch0c2;
        TEdit *Tn7bcchch0c2;
        TEdit *Numreqbpcch1c2;
        TEdit *Numreqegprsbpcch1c2;
        TEdit *Numreqcs3cs4bpcch1c2;
        TEdit *Cell2;
        TGroupBox *Edgec3Panel;
        TLabel *Label101;
        TLabel *Label102;
        TLabel *Label103;
        TLabel *Label104;
        TLabel *Label105;
        TEdit *Numreqbpcch0c3;
        TEdit *Numreqegprsbpcch0c3;
        TEdit *Numreqcs3cs4bpcch0c3;
        TEdit *Tn7bcchch0c3;
        TEdit *Numreqbpcch1c3;
        TEdit *Numreqegprsbpcch1c3;
        TEdit *Numreqcs3cs4bpcch1c3;
        TEdit *Cell3;
        TGroupBox *Edgec4Panel;
        TLabel *Label107;
        TLabel *Label108;
        TLabel *Label109;
        TLabel *Label110;
        TLabel *Label111;
        TLabel *Label112;
        TEdit *Numreqbpcch0c4;
        TEdit *Numreqegprsbpcch0c4;
        TEdit *Numreqcs3cs4bpcch0c4;
        TEdit *Tn7bcchch0c4;
        TEdit *Numreqbpcch1c4;
        TEdit *Numreqegprsbpcch1c4;
        TEdit *Numreqcs3cs4bpcch1c4;
        TEdit *Cell4;
        TCheckBox *Chgr1c1cbox;
        TCheckBox *Chgr2c1cbox;
        TEdit *Numreqbpcch2c1;
        TEdit *Numreqegprsbpcch2c1;
        TEdit *Numreqcs3cs4bpcch2c1;
        TCheckBox *Chgr3c1cbox;
        TEdit *Numreqbpcch3c1;
        TEdit *Numreqegprsbpcch3c1;
        TEdit *Numreqcs3cs4bpcch3c1;
        TLabel *Label96;
        TCheckBox *Chgr1c2cbox;
        TCheckBox *Chgr2c2cbox;
        TCheckBox *Chgr3c2cbox;
        TEdit *Numreqbpcch2c2;
        TEdit *Numreqegprsbpcch2c2;
        TEdit *Numreqcs3cs4bpcch2c2;
        TEdit *Numreqbpcch3c2;
        TEdit *Numreqegprsbpcch3c2;
        TEdit *Numreqcs3cs4bpcch3c2;
        TLabel *Label98;
        TLabel *Label106;
        TCheckBox *Chgr1c3cbox;
        TCheckBox *Chgr2c3cbox;
        TCheckBox *Chgr3c3cbox;
        TEdit *Numreqbpcch2c3;
        TEdit *Numreqegprsbpcch2c3;
        TEdit *Numreqcs3cs4bpcch2c3;
        TEdit *Numreqbpcch3c3;
        TEdit *Numreqegprsbpcch3c3;
        TEdit *Numreqcs3cs4bpcch3c3;
        TCheckBox *Chgr1c4cbox;
        TCheckBox *Chgr2c4cbox;
        TCheckBox *Chgr3c4cbox;
        TEdit *Numreqbpcch2c4;
        TEdit *Numreqegprsbpcch2c4;
        TEdit *Numreqcs3cs4bpcch2c4;
        TEdit *Numreqbpcch3c4;
        TEdit *Numreqegprsbpcch3c4;
        TEdit *Numreqcs3cs4bpcch3c4;
        TCheckBox *SubCellCheckBox;
        TPanel *CheckPanel;
        TEdit *Tn7bcchch1c1;
        TEdit *Tn7bcchch2c1;
        TEdit *Tn7bcchch3c1;
        TEdit *Tn7bcchch1c2;
        TEdit *Tn7bcchch2c2;
        TEdit *Tn7bcchch3c2;
        TEdit *Tn7bcchch1c3;
        TEdit *Tn7bcchch2c3;
        TEdit *Tn7bcchch3c3;
        TEdit *Tn7bcchch1c4;
        TEdit *Tn7bcchch2c4;
        TEdit *Tn7bcchch3c4;
        TEdit *Dcpk1Edit;
        TEdit *Devk1Edit;
        TCheckBox *Devk1CheckBox;
        TCheckBox *Devk2CheckBox;
        TEdit *Dcpk2Edit;
        TEdit *Devk2Edit;
        TCheckBox *Devk3CheckBox;
        TEdit *Dcpk3Edit;
        TEdit *Devk3Edit;
        TCheckBox *Devk4CheckBox;
        TEdit *Dcpk4Edit;
        TEdit *Devk4Edit;
        TEdit *Dcpek1Edit;
        TEdit *Devek1Edit;
        TEdit *Dcpek2Edit;
        TEdit *Devek2Edit;
        TEdit *Dcpek3Edit;
        TEdit *Devek3Edit;
        TEdit *Dcpek4Edit;
        TEdit *Devek4Edit;
        TPanel *FinishPanel;
        TPanel *CellsPanel;
        TPanel *RldepqonPanel;
        TPanel *ClearPanel;
        TPanel *InitPanel;
        TCheckBox *LoaddefCheckBox;
        TWinSkinForm *WinSkinForm1;
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall Button2Click(TObject *Sender);
        void __fastcall TgsayiChange(TObject *Sender);
        void __fastcall RbltsayiChange(TObject *Sender);
        void __fastcall Tpk1Change(TObject *Sender);
        void __fastcall FhopChange(TObject *Sender);
        void __fastcall Skt1Click(TObject *Sender);
        void __fastcall Skt2Click(TObject *Sender);
        void __fastcall Skt3Click(TObject *Sender);
        void __fastcall Skt4Click(TObject *Sender);
        void __fastcall DesktClick(TObject *Sender);
        void __fastcall KsayiChange(TObject *Sender);
        void __fastcall Tpk2Change(TObject *Sender);
        void __fastcall Tpk3Change(TObject *Sender);
        void __fastcall Tpk4Change(TObject *Sender);
        void __fastcall Tru1k2Click(TObject *Sender);
        void __fastcall Tru1k3Click(TObject *Sender);
        void __fastcall Tru2k3Click(TObject *Sender);
        void __fastcall Tru3k3Click(TObject *Sender);
        void __fastcall Tru4k3Click(TObject *Sender);
        void __fastcall Tru5k3Click(TObject *Sender);
        void __fastcall Tru6k3Click(TObject *Sender);
        void __fastcall Tru7k3Click(TObject *Sender);
        void __fastcall Tru8k3Click(TObject *Sender);
        void __fastcall Tru9k3Click(TObject *Sender);
        void __fastcall Tru10k3Click(TObject *Sender);
        void __fastcall Tru11k3Click(TObject *Sender);
        void __fastcall Tru12k3Click(TObject *Sender);
        void __fastcall Tru1k4Click(TObject *Sender);
        void __fastcall Tru3k4Click(TObject *Sender);
        void __fastcall Tru2k4Click(TObject *Sender);
        void __fastcall Tru4k4Click(TObject *Sender);
        void __fastcall Tru5k4Click(TObject *Sender);
        void __fastcall Tru6k4Click(TObject *Sender);
        void __fastcall Tru7k4Click(TObject *Sender);
        void __fastcall Tru8k4Click(TObject *Sender);
        void __fastcall Tru9k4Click(TObject *Sender);
        void __fastcall Tru10k4Click(TObject *Sender);
        void __fastcall Tru11k4Click(TObject *Sender);
        void __fastcall Tru12k4Click(TObject *Sender);
        void __fastcall Tg1Change(TObject *Sender);
        void __fastcall Tg2Change(TObject *Sender);
        void __fastcall Tg3Change(TObject *Sender);
        void __fastcall Tg4Change(TObject *Sender);
        void __fastcall SitenoChange(TObject *Sender);
        void __fastcall Rblt1Change(TObject *Sender);
        void __fastcall Rblt2Change(TObject *Sender);
        void __fastcall Rblt3Change(TObject *Sender);
        void __fastcall Rblt4Change(TObject *Sender);
        void __fastcall Odp23k1Change(TObject *Sender);
        void __fastcall Odp23k2Change(TObject *Sender);
        void __fastcall Odp23k3Change(TObject *Sender);
        void __fastcall Odp23k4Change(TObject *Sender);
        void __fastcall SeksayChange(TObject *Sender);
        void __fastcall CsystypeChange(TObject *Sender);
        void __fastcall Tru2k1Click(TObject *Sender);
        void __fastcall Tru3k1Click(TObject *Sender);
        void __fastcall Tru4k1Click(TObject *Sender);
        void __fastcall Tru5k1Click(TObject *Sender);
        void __fastcall Tru6k1Click(TObject *Sender);
        void __fastcall Tru7k1Click(TObject *Sender);
        void __fastcall Tru8k1Click(TObject *Sender);
        void __fastcall Tru9k1Click(TObject *Sender);
        void __fastcall Tru10k1Click(TObject *Sender);
        void __fastcall Tru11k1Click(TObject *Sender);
        void __fastcall Tru12k1Click(TObject *Sender);
        void __fastcall Tru1k1Click(TObject *Sender);
        void __fastcall Tru2k2Click(TObject *Sender);
        void __fastcall Tru3k2Click(TObject *Sender);
        void __fastcall Tru4k2Click(TObject *Sender);
        void __fastcall Tru5k2Click(TObject *Sender);
        void __fastcall Tru6k2Click(TObject *Sender);
        void __fastcall Tru7k2Click(TObject *Sender);
        void __fastcall Tru8k2Click(TObject *Sender);
        void __fastcall Tru9k2Click(TObject *Sender);
        void __fastcall Tru10k2Click(TObject *Sender);
        void __fastcall Tru11k2Click(TObject *Sender);
        void __fastcall Tru12k2Click(TObject *Sender);
        void __fastcall IdTelnet1DataAvailable(AnsiString Buffer);
        void __fastcall Loadfromsystem1Click(TObject *Sender);
        void __fastcall IdTelnet1Disconnected(TObject *Sender);
        void __fastcall TgbufferChange(TObject *Sender);
        void __fastcall Pbodp01k1Click(TObject *Sender);
        void __fastcall Pbodp23k1Click(TObject *Sender);
        void __fastcall Pbodp01k2Click(TObject *Sender);
        void __fastcall Pbodp01k3Click(TObject *Sender);
        void __fastcall Pbodp01k4Click(TObject *Sender);
        void __fastcall Pbodp23k2Click(TObject *Sender);
        void __fastcall Pbodp23k3Click(TObject *Sender);
        void __fastcall Pbodp23k4Click(TObject *Sender);
        void __fastcall EdgevarClick(TObject *Sender);
        void __fastcall EdgeyoxduClick(TObject *Sender);
        void __fastcall Timerc1Timer(TObject *Sender);
        void __fastcall Cell1Change(TObject *Sender);
        void __fastcall Etru1k1Click(TObject *Sender);
        void __fastcall Etru2k1Click(TObject *Sender);
        void __fastcall Etru3k1Click(TObject *Sender);
        void __fastcall Etru4k1Click(TObject *Sender);
        void __fastcall Etru5k1Click(TObject *Sender);
        void __fastcall Etru6k1Click(TObject *Sender);
        void __fastcall Etru7k1Click(TObject *Sender);
        void __fastcall Etru8k1Click(TObject *Sender);
        void __fastcall Etru9k1Click(TObject *Sender);
        void __fastcall Etru10k1Click(TObject *Sender);
        void __fastcall Etru11k1Click(TObject *Sender);
        void __fastcall Etru12k1Click(TObject *Sender);
        void __fastcall Etru1k2Click(TObject *Sender);
        void __fastcall Etru2k2Click(TObject *Sender);
        void __fastcall Etru3k2Click(TObject *Sender);
        void __fastcall Etru4k2Click(TObject *Sender);
        void __fastcall Etru5k2Click(TObject *Sender);
        void __fastcall Etru6k2Click(TObject *Sender);
        void __fastcall Etru7k2Click(TObject *Sender);
        void __fastcall Etru8k2Click(TObject *Sender);
        void __fastcall Etru9k2Click(TObject *Sender);
        void __fastcall Etru10k2Click(TObject *Sender);
        void __fastcall Etru11k2Click(TObject *Sender);
        void __fastcall Etru12k2Click(TObject *Sender);
        void __fastcall Etru1k3Click(TObject *Sender);
        void __fastcall Etru2k3Click(TObject *Sender);
        void __fastcall Etru3k3Click(TObject *Sender);
        void __fastcall Etru4k3Click(TObject *Sender);
        void __fastcall Etru5k3Click(TObject *Sender);
        void __fastcall Etru6k3Click(TObject *Sender);
        void __fastcall Etru7k3Click(TObject *Sender);
        void __fastcall Etru8k3Click(TObject *Sender);
        void __fastcall Etru9k3Click(TObject *Sender);
        void __fastcall Etru10k3Click(TObject *Sender);
        void __fastcall Etru11k3Click(TObject *Sender);
        void __fastcall Etru12k3Click(TObject *Sender);
        void __fastcall Etru1k4Click(TObject *Sender);
        void __fastcall Etru2k4Click(TObject *Sender);
        void __fastcall Etru3k4Click(TObject *Sender);
        void __fastcall Etru4k4Click(TObject *Sender);
        void __fastcall Etru5k4Click(TObject *Sender);
        void __fastcall Etru6k4Click(TObject *Sender);
        void __fastcall Etru7k4Click(TObject *Sender);
        void __fastcall Etru8k4Click(TObject *Sender);
        void __fastcall Etru9k4Click(TObject *Sender);
        void __fastcall Etru10k4Click(TObject *Sender);
        void __fastcall Etru11k4Click(TObject *Sender);
        void __fastcall Etru12k4Click(TObject *Sender);
        void __fastcall Eodp01k1Click(TObject *Sender);
        void __fastcall Eodp23k1Click(TObject *Sender);
        void __fastcall Eodp01k2Click(TObject *Sender);
        void __fastcall Eodp23k2Click(TObject *Sender);
        void __fastcall Eodp01k3Click(TObject *Sender);
        void __fastcall Eodp01k4Click(TObject *Sender);
        void __fastcall Eodp23k3Click(TObject *Sender);
        void __fastcall Eodp23k4Click(TObject *Sender);
        void __fastcall RbltbufferDblClick(TObject *Sender);
        void __fastcall Swverk1Change(TObject *Sender);
        void __fastcall RxtcpPanelClick(TObject *Sender);
        void __fastcall RxappPanelClick(TObject *Sender);
        void __fastcall RlbdpPanelClick(TObject *Sender);
        void __fastcall RxmopPanelClick(TObject *Sender);
        void __fastcall RldepPanelClick(TObject *Sender);
        void __fastcall Rxmoptruk1PanelClick(TObject *Sender);
        void __fastcall Cell1PanelClick(TObject *Sender);
        void __fastcall Chgr1c1cboxClick(TObject *Sender);
        void __fastcall Chgr2c1cboxClick(TObject *Sender);
        void __fastcall Chgr3c1cboxClick(TObject *Sender);
        void __fastcall Chgr1c2cboxClick(TObject *Sender);
        void __fastcall Chgr1c3cboxClick(TObject *Sender);
        void __fastcall Chgr3c3cboxClick(TObject *Sender);
        void __fastcall Chgr1c4cboxClick(TObject *Sender);
        void __fastcall Chgr2c2cboxClick(TObject *Sender);
        void __fastcall Chgr2c3cboxClick(TObject *Sender);
        void __fastcall Chgr2c4cboxClick(TObject *Sender);
        void __fastcall Chgr3c2cboxClick(TObject *Sender);
        void __fastcall Chgr3c4cboxClick(TObject *Sender);
        void __fastcall SubCellCheckBoxClick(TObject *Sender);
        void __fastcall Memo1DblClick(TObject *Sender);
        void __fastcall Rxmoptruk2PanelClick(TObject *Sender);
        void __fastcall Rxmoptruk3PanelClick(TObject *Sender);
        void __fastcall Rxmoptruk4PanelClick(TObject *Sender);
        void __fastcall Cell2PanelClick(TObject *Sender);
        void __fastcall Cell3PanelClick(TObject *Sender);
        void __fastcall Cell4PanelClick(TObject *Sender);
        void __fastcall AdditionPanelClick(TObject *Sender);
        void __fastcall CellsPanelClick(TObject *Sender);
        void __fastcall FinishPanelClick(TObject *Sender);
        void __fastcall RldepqonPanelClick(TObject *Sender);
        void __fastcall ClearPanelDblClick(TObject *Sender);
        void __fastcall InitPanelDblClick(TObject *Sender);
        void __fastcall TgbufferDblClick(TObject *Sender);
        void __fastcall Devek1EditDblClick(TObject *Sender);
        void __fastcall Devk1EditDblClick(TObject *Sender);
        void __fastcall Devk2EditDblClick(TObject *Sender);
        void __fastcall Devk3EditDblClick(TObject *Sender);
        void __fastcall Devk4EditDblClick(TObject *Sender);
        void __fastcall Devek3EditDblClick(TObject *Sender);
        void __fastcall Devek4EditDblClick(TObject *Sender);
        void __fastcall Devek2EditDblClick(TObject *Sender);
        void __fastcall LoaddefCheckBoxClick(TObject *Sender);
       
private:	// User declarations
public:		// User declarations

String Servis;
int p,l,SAY;
String Edits;


        __fastcall TForm3(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm3 *Form3;
//---------------------------------------------------------------------------
#endif
